const db = supabaseClient; const $ = id => document.getElementById(id); const form=$('signupForm'),button=$('signupButton'),message=$('message');
function show(t,type=''){message.textContent=t;message.className=`auth-message ${type}`}
function reset(){button.disabled=false;button.querySelector('span').textContent='Create Shop Account';button.querySelector('b').textContent='→'}
function fail(t){show(t,'error');reset();return false}
function score(v){let s=0;if(v.length>=8)s++;if(/[A-Z]/.test(v))s++;if(/[a-z]/.test(v))s++;if(/\d/.test(v))s++;if(/[^A-Za-z0-9]/.test(v))s++;return Math.min(s,5)}
$('password').addEventListener('input',e=>$('passwordMeter').style.width=`${score(e.target.value)*20}%`);
document.querySelectorAll('.password-toggle').forEach(t=>t.addEventListener('click',()=>{const i=$(t.dataset.target);i.type=i.type==='password'?'text':'password';t.textContent=i.type==='password'?'Show':'Hide'}));
async function invoke(name,body){const r=await db.functions.invoke(name,{body});if(r.error)throw r.error;if(r.data?.error)throw new Error(r.data.error);return r.data}
async function registrationPayment(user,shop){
 if(!window.Razorpay)throw new Error('Razorpay Checkout load नहीं हुआ.');
 const c=await invoke('create-shop-registration-payment',{user_id:user.id});
 await new Promise((resolve,reject)=>{let done=false;const ok=()=>{if(!done){done=true;resolve()}};const no=e=>{if(!done){done=true;reject(e)}};const r=new Razorpay({key:c.key_id,amount:c.amount,currency:'INR',name:'Sahil Online Services',description:'Shop Registration ₹2',order_id:c.razorpay_order_id,prefill:{name:user.user_metadata?.owner_name,email:user.email,contact:user.user_metadata?.mobile},handler:async res=>{try{await invoke('verify-shop-registration',{user_id:user.id,shop_id:shop.id,razorpay_order_id:res.razorpay_order_id,razorpay_payment_id:res.razorpay_payment_id,razorpay_signature:res.razorpay_signature});ok()}catch(e){no(e)}},modal:{ondismiss:()=>no(new Error('Registration payment cancelled.'))}});r.on('payment.failed',x=>no(new Error(x?.error?.description||'Registration payment failed.')));r.open()})
}
form.addEventListener('submit',async e=>{e.preventDefault();button.disabled=true;button.querySelector('span').textContent='Creating & verifying…';show('');const shopName=$('shopName').value.trim(),ownerName=$('ownerName').value.trim(),mobile=$('mobile').value.replace(/\D/g,''),email=$('email').value.trim().toLowerCase(),password=$('password').value,confirm=$('confirmPassword').value;if(shopName.length<2)return fail('Please enter your Shop Name.');if(ownerName.length<2)return fail('Please enter the Owner Name.');if(!/^\d{10}$/.test(mobile))return fail('Please enter a valid 10-digit mobile number.');if(!/^\S+@\S+\.\S+$/.test(email))return fail('Please enter a valid email address.');if(password.length<8)return fail('Password must contain at least 8 characters.');if(password!==confirm)return fail('Passwords do not match.');try{const {data,error}=await db.auth.signUp({email,password,options:{data:{account_type:'shop_owner',shop_name:shopName,owner_name:ownerName,mobile}}});if(error)throw error;if(!data?.user)throw new Error('Account could not be created.');if(!data.session){show('Account created. Verify your email, then login. The ₹2 registration payment will be started from the verified session.','success');form.reset();$('passwordMeter').style.width='0%';return}const {data:shop,error:se}=await db.from('shops').select('id,shop_id,shop_name').eq('owner_user_id',data.user.id).single();if(se||!shop)throw se||new Error('Shop profile is not ready yet.');await registrationPayment(data.user,shop);show('₹2 verified. Your 2-day free trial is active. Opening dashboard…','success');setTimeout(()=>location.href='shop-dashboard.html',700)}catch(err){let t=err?.message||'Unable to create account.';if(t.toLowerCase().includes('already registered'))t='This email is already registered. Please login.';show(t,'error')}finally{reset()}});
