(function(){'use strict';
const db=window.supabaseClient||window.db; const $=id=>document.getElementById(id); let payout=null;
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function toast(m){if(window.toast) window.toast(m); else alert(m);}
async function getShop(){const u=(await db.auth.getUser()).data.user;if(!u)return null;const r=await db.from('shops').select('*').eq('owner_user_id',u.id).limit(1);return r.data?.[0]||null;}
function syncPayoutFields(){const method=$('payoutMethod')?.value||'UPI'; const bank=$('bankPayoutFields'), upi=$('upiPayoutFields'); if(bank)bank.style.display=method==='BANK'?'block':'none'; if(upi)upi.style.display=method==='UPI'?'block':'none';}
async function load(){const sh=await getShop(); if(!sh)return; const r=await db.from('shop_payout_details').select('*').eq('shop_id',sh.id).maybeSingle(); payout=r.data||null; if($('payoutMethod'))$('payoutMethod').value=payout?.payout_method||'UPI'; $('payoutHolder').value=payout?.account_holder_name||''; $('payoutBank').value=payout?.bank_name||''; $('payoutAccount').value=payout?.account_number||''; $('payoutIfsc').value=payout?.ifsc_code||''; $('payoutUpi').value=payout?.upi_id||''; $('payoutMobile').value=payout?.registered_mobile||sh.mobile||''; syncPayoutFields(); if($('payoutStatus'))$('payoutStatus').textContent='Verification: '+(payout?.verification_status||'Not saved')+(payout?.verification_note?' — '+payout.verification_note:'');}
async function save(){const sh=await getShop();if(!sh)return;const method=$('payoutMethod').value;const row={shop_id:sh.id,payout_method:method,account_holder_name:$('payoutHolder').value.trim()||null,bank_name:$('payoutBank').value.trim()||null,account_number:$('payoutAccount').value.trim()||null,ifsc_code:$('payoutIfsc').value.trim().toUpperCase()||null,upi_id:$('payoutUpi').value.trim().toLowerCase()||null,registered_mobile:$('payoutMobile').value.trim()||null,verification_status:'PENDING'};if(method==='UPI'&&!row.upi_id){toast('UPI ID डालें');return;}if(method==='BANK'&&(!row.account_holder_name||!row.account_number||!row.ifsc_code)){toast('Bank account holder, account number और IFSC भरें');return;}const r=await db.from('shop_payout_details').upsert(row,{onConflict:'shop_id'});if(r.error){toast('Save failed: '+r.error.message);return;}toast('Payout details saved. Verification pending.');await load();}
async function withdraw(){const amount=Number($('withdrawAmount').value);if(!amount||amount<=0){toast('Valid amount डालें');return;}const r=await db.rpc('request_shop_withdrawal',{p_amount:amount});if(r.error){toast('Withdrawal failed: '+r.error.message);return;}toast('Withdrawal request submitted: '+r.data);$('withdrawAmount').value='';}
window.loadShopPayout=load; document.addEventListener('DOMContentLoaded',()=>{setTimeout(()=>{if($('payoutMethod'))$('payoutMethod').onchange=syncPayoutFields;if($('savePayout'))$('savePayout').onclick=save;if($('requestWithdrawal'))$('requestWithdrawal').onclick=withdraw;syncPayoutFields();load();},1000);});})();